# Generated by Django 4.2.11 on 2025-11-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=100)),
                ('nombre_archivo', models.CharField(max_length=200)),
                ('total_registros', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('tiempo_proceso', models.FloatField(blank=True, help_text='Tiempo de procesamiento en segundos', null=True)),
            ],
            options={
                'verbose_name': 'Carga de Stock',
                'verbose_name_plural': 'Cargas de Stock',
                'db_table': 'cargas_stock',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='StockSAP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, db_column='#', help_text='Número correlativo del archivo', null=True)),
                ('Codigo', models.CharField(db_index=True, help_text='Código del producto (ItemCode en maestro)', max_length=100)),
                ('Descripcion', models.CharField(help_text='Descripción del producto', max_length=500)),
                ('Cod_Grupo', models.IntegerField(blank=True, db_column='Cod.Grupo', help_text='Código del grupo', null=True)),
                ('Descripcion_Grupo', models.CharField(db_column='Descripcion Grupo', help_text='Nombre del grupo', max_length=200)),
                ('Cod_Bodega', models.CharField(db_column='Cod.Bodega', db_index=True, help_text='Código de la bodega', max_length=50)),
                ('Descripcion_Bodega', models.CharField(db_column='Descripcion Bodega', help_text='Nombre de la bodega', max_length=200)),
                ('Ubicacion', models.CharField(blank=True, help_text='Ubicación física en bodega', max_length=100, null=True)),
                ('Ubicacion_2', models.CharField(blank=True, db_column='Ubicacion 2', help_text='Ubicación secundaria', max_length=100, null=True)),
                ('Stock', models.DecimalField(decimal_places=2, help_text='Cantidad disponible', max_digits=12)),
                ('Precio_USD', models.DecimalField(blank=True, db_column='Precio $', decimal_places=2, help_text='Precio unitario en dólares', max_digits=12, null=True)),
                ('Total_USD', models.DecimalField(blank=True, db_column='Total $', decimal_places=2, help_text='Valor total (Stock × Precio)', max_digits=12, null=True)),
                ('Categoria', models.DecimalField(blank=True, decimal_places=2, help_text='Categoría del producto', max_digits=12, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última carga')),
            ],
            options={
                'verbose_name': 'Stock SAP',
                'verbose_name_plural': 'Stock SAP',
                'db_table': 'stock_sap',
                'ordering': ['Codigo', 'Cod_Bodega'],
                'indexes': [models.Index(fields=['Codigo'], name='idx_stock_codigo'), models.Index(fields=['Cod_Bodega'], name='idx_stock_bodega'), models.Index(fields=['Codigo', 'Cod_Bodega'], name='idx_stock_codigo_bodega')],
            },
        ),
    ]
