# Generated by Django 4.2.11 on 2025-11-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargastock',
            options={'managed': False, 'ordering': ['-fecha_carga'], 'verbose_name': 'Carga de Stock', 'verbose_name_plural': 'Cargas de Stock'},
        ),
        migrations.AlterModelOptions(
            name='stocksap',
            options={'managed': False, 'ordering': ['codigo', 'bodega'], 'verbose_name': 'Stock SAP', 'verbose_name_plural': 'Stock SAP'},
        ),
    ]
