# Generated by Django 4.2.11 on 2025-11-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_cargastock_options_alter_stocksap_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cargastock',
            table='carga_stock',
        ),
        migrations.AlterModelTable(
            name='stocksap',
            table='stock',
        ),
    ]
