# Generated by Django 5.2.6 on 2025-11-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre completo'),
        ),
    ]
