# Generated by Django 4.2.11 on 2025-11-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_nombre_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: 013-01, 013-PP, etc.', max_length=50, unique=True, verbose_name='Código de bodega')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la bodega')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodegas',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='bodegas_codigo_bf530c_idx'), models.Index(fields=['activa'], name='bodegas_activa_076620_idx')],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='bodegas_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Bodegas que este usuario puede gestionar', related_name='usuarios', to='core.bodega', verbose_name='Bodegas asignadas'),
        ),
    ]
