# Generated by Django 6.0 on 2025-12-14 23:51

from django.db import migrations, models


def seed_tipos_solicitud(apps, schema_editor):
    """Pobla la tabla de tipos de solicitud con los tipos iniciales"""
    TipoSolicitud = apps.get_model('configuracion', 'TipoSolicitud')
    
    tipos_iniciales = [
        ('PC', 'PC', 'Pedido Cliente', 10, 'file-text', 'primary'),
        ('OC', 'OC', 'Orden de Compra', 20, 'file-earmark-text', 'info'),
        ('EM', 'Emergencia', 'Solicitud de Emergencia', 30, 'exclamation-triangle', 'danger'),
        ('ST', 'Solicitud de Traslado', 'Solicitud de Traslado Interno', 40, 'arrow-right-circle', 'success'),
        ('OF', 'Oficina', 'Pedido de Oficina', 50, 'briefcase', 'secondary'),
        ('RM', 'Retiro de Mercancías', 'Retiro de Mercancías por Cliente', 60, 'box-arrow-right', 'warning'),
    ]
    
    for codigo, nombre, descripcion, orden, icono, color in tipos_iniciales:
        TipoSolicitud.objects.update_or_create(
            codigo=codigo,
            defaults={
                'nombre': nombre,
                'descripcion': descripcion,
                'orden': orden,
                'icono': icono,
                'color': color,
                'activo': True,
            },
        )


def rollback_tipos_solicitud(apps, schema_editor):
    """Elimina los tipos de solicitud (rollback)"""
    TipoSolicitud = apps.get_model('configuracion', 'TipoSolicitud')
    TipoSolicitud.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_add_finalizado_bulto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('icono', models.CharField(blank=True, default='file-text', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(blank=True, default='primary', max_length=30, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Tipo de solicitud',
                'verbose_name_plural': 'Tipos de solicitud',
                'db_table': 'config_tipos_solicitud',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.AlterField(
            model_name='estadoworkflow',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.RunPython(seed_tipos_solicitud, rollback_tipos_solicitud),
    ]
