# Generated by Django 6.0 on 2026-01-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_tiposolicitud_alter_estadoworkflow_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True, verbose_name='Fecha del feriado')),
                ('nombre', models.CharField(help_text='Ej: Año Nuevo, Fiestas Patrias, etc.', max_length=100, verbose_name='Nombre del feriado')),
                ('descripcion', models.TextField(blank=True, help_text='Información adicional sobre el feriado', verbose_name='Descripción')),
                ('es_inamovible', models.BooleanField(default=True, help_text='Si es False, puede moverse al lunes siguiente', verbose_name='¿Es inamovible?')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ignorar este feriado en cálculos', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'db_table': 'config_feriados',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['fecha', 'activo'], name='idx_feriado_fecha_activo')],
            },
        ),
    ]
