# Generated by Django 6.0 on 2026-05-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_feriado'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feriado',
            name='idx_feriado_fecha_activo',
        ),
        migrations.DeleteModel(
            name='Feriado',
        ),
    ]
