# Generated by Django 4.2.11 on 2025-11-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('total_productos', models.IntegerField(default=0)),
                ('total_bodegas', models.IntegerField(default=0)),
                ('archivo_url', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('activo', 'Activo'), ('expirado', 'Expirado'), ('error', 'Error')], default='procesando', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'carga_stock',
                'ordering': ['-fecha_carga'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cod_grupo', models.IntegerField(blank=True, null=True)),
                ('descripcion_grupo', models.CharField(blank=True, max_length=200, null=True)),
                ('bodega', models.CharField(max_length=20)),
                ('bodega_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_2', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_disponible', models.IntegerField(default=0)),
                ('stock_reservado', models.IntegerField(default=0)),
                ('precio', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock',
                'ordering': ['codigo', 'bodega'],
                'managed': False,
            },
        ),
    ]
