# Generated by Django 5.2.6 on 2025-11-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_stockreserva_bodegatransferencia'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bodegatransferencia',
            new_name='bodega_tran_numero__724cbe_idx',
            old_name='bodega_transfer_numero',
        ),
        migrations.RenameIndex(
            model_name='bodegatransferencia',
            new_name='bodega_tran_fecha_t_89d2eb_idx',
            old_name='bodega_transfer_fecha_hora',
        ),
        migrations.RenameIndex(
            model_name='bodegatransferencia',
            new_name='bodega_tran_bodega__9b2092_idx',
            old_name='bodega_transfer_origen',
        ),
        migrations.RenameIndex(
            model_name='stockreserva',
            new_name='bodega_stoc_codigo_fe32bb_idx',
            old_name='bodega_reserva_cod_bod',
        ),
        migrations.RenameIndex(
            model_name='stockreserva',
            new_name='bodega_stoc_estado_08c860_idx',
            old_name='bodega_reserva_estado',
        ),
        migrations.AlterField(
            model_name='stockreserva',
            name='bodega',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stockreserva',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
