# Generated by Django 4.2.11 on 2025-12-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0002_auto_config_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulto',
            name='fecha_embalaje',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha embalaje'),
        ),
    ]
