# Generated by Django 6.0 on 2026-05-03 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0004_change_solicitudes_to_foreignkey'),
        ('solicitudes', '0018_fix_fecha_despachado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulto',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bultos', to='solicitudes.solicitud', verbose_name='Solicitud'),
        ),
    ]
