# Generated by Django 5.2.6 on 2025-11-23 19:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('hora_solicitud', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de solicitud')),
                ('tipo', models.CharField(choices=[('PC', 'PC'), ('OC', 'OC'), ('EM', 'Emergencia'), ('ST', 'Stock'), ('OF', 'Oficina')], max_length=2, verbose_name='Tipo de solicitud')),
                ('cliente', models.CharField(db_index=True, max_length=200, verbose_name='Cliente')),
                ('codigo', models.CharField(db_index=True, max_length=50, verbose_name='Código de producto')),
                ('descripcion', models.TextField(verbose_name='Descripción del producto')),
                ('cantidad_solicitada', models.IntegerField(verbose_name='Cantidad solicitada')),
                ('bodega', models.CharField(max_length=50, verbose_name='Bodega origen')),
                ('observacion', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_despacho', 'En Despacho'), ('embalado', 'Embalado'), ('despachado', 'Despachado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('urgente', models.BooleanField(db_index=True, default=False, verbose_name='¿Es urgente?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitudes',
                'ordering': ['-fecha_solicitud', '-hora_solicitud'],
                'indexes': [models.Index(fields=['estado', 'urgente'], name='solicitudes_estado_a03808_idx'), models.Index(fields=['cliente'], name='solicitudes_cliente_23301a_idx'), models.Index(fields=['-fecha_solicitud'], name='solicitudes_fecha_s_d55ed4_idx'), models.Index(fields=['codigo'], name='solicitudes_codigo_d87112_idx')],
            },
        ),
    ]
