# Generated by Django 5.2.6 on 2025-11-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_add_fields_transporte_numero'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solicitud',
            new_name='solicitudes_tipo_a7b99a_idx',
            old_name='solicitudes_tipo_crea_idx',
        ),
    ]
