# Generated by Django 5.2.6 on 2025-11-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicituddetalle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solicituddetalle',
            new_name='solicitudes_solicit_0ab720_idx',
            old_name='solicitude_solicitu_5c39e4_idx',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='transporte',
            field=models.CharField(choices=[('PESCO', 'Camión PESCO'), ('VARMONTT', 'Varmontt'), ('STARKEN', 'Starken'), ('KAIZEN', 'Kaizen'), ('RETIRA_CLIENTE', 'Retira cliente'), ('OTRO', 'Otro / Coordinado')], default='PESCO', max_length=20, verbose_name='Transporte'),
        ),
    ]
