# Generated by Django 5.2.6 on 2025-11-26 01:54

import solicitudes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_alter_solicitud_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateField(db_index=True, default=solicitudes.models.get_chile_date, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora_solicitud',
            field=models.TimeField(default=solicitudes.models.get_chile_time, verbose_name='Hora de solicitud'),
        ),
    ]
