# Generated by Django 5.2.6 on 2025-11-26 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_alter_solicitud_fecha_solicitud_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='solicitud',
            name='solicitudes_estado_a03808_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitud',
            name='solicitudes_fecha_s_d55ed4_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitud',
            name='solicitudes_tipo_a7b99a_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitud',
            new_name='idx_cliente',
            old_name='solicitudes_cliente_23301a_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitud',
            new_name='idx_codigo',
            old_name='solicitudes_codigo_d87112_idx',
        ),
        migrations.RenameIndex(
            model_name='solicituddetalle',
            new_name='idx_detalle_sol_codigo',
            old_name='solicitudes_solicit_0ab720_idx',
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado'], name='idx_estado'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado', 'id'], name='idx_estado_id'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['numero_pedido'], name='idx_numero_pedido'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['numero_st'], name='idx_numero_st'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['tipo'], name='idx_tipo'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado', 'tipo'], name='idx_estado_tipo'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['urgente', 'estado'], name='idx_urgente_estado'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['-fecha_solicitud', '-hora_solicitud'], name='idx_fecha_hora'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['tipo', 'numero_st'], name='idx_tipo_st'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['solicitante'], name='idx_solicitante'),
        ),
        migrations.AddIndex(
            model_name='solicituddetalle',
            index=models.Index(fields=['solicitud'], name='idx_detalle_solicitud'),
        ),
        migrations.AddIndex(
            model_name='solicituddetalle',
            index=models.Index(fields=['codigo'], name='idx_detalle_codigo'),
        ),
    ]
