# Generated by Django 4.2.11 on 2025-11-30 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0008_add_optimized_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddetalle',
            name='bodega',
            field=models.CharField(blank=True, db_index=True, help_text='Bodega donde se encuentra este producto', max_length=50, verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='solicituddetalle',
            name='estado_bodega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('preparado', 'Preparado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado en bodega'),
        ),
        migrations.AddField(
            model_name='solicituddetalle',
            name='fecha_preparacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de preparación'),
        ),
        migrations.AddField(
            model_name='solicituddetalle',
            name='preparado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_preparados', to=settings.AUTH_USER_MODEL, verbose_name='Preparado por'),
        ),
        migrations.AddIndex(
            model_name='solicituddetalle',
            index=models.Index(fields=['bodega'], name='idx_detalle_bodega'),
        ),
        migrations.AddIndex(
            model_name='solicituddetalle',
            index=models.Index(fields=['estado_bodega'], name='idx_detalle_estado_bod'),
        ),
        migrations.AddIndex(
            model_name='solicituddetalle',
            index=models.Index(fields=['bodega', 'estado_bodega'], name='idx_detalle_bod_estado'),
        ),
    ]
