# Generated by Django 4.2.11 on 2025-12-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_auto_config_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='afecta_stock',
            field=models.BooleanField(default=True, help_text='Si es False, no se descuenta stock (órdenes especiales, traslados, etc.)', verbose_name='¿Afecta stock?'),
        ),
    ]
