# Generated by Django 4.2.11 on 2025-12-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_solicitud_afecta_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='numero_guia_despacho',
            field=models.CharField(blank=True, help_text='Número de guía o factura que confirma el despacho', max_length=100, verbose_name='Número de Guía/Factura'),
        ),
    ]
