# Generated by Django 6.0 on 2025-12-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0015_agregar_numero_guia_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('PC', 'PC'), ('OC', 'OC'), ('EM', 'Emergencia'), ('ST', 'Solicitud de Traslado'), ('OF', 'Oficina'), ('RM', 'Retiro de Mercancías')], max_length=10, verbose_name='Tipo de solicitud'),
        ),
    ]
