# Generated by Django 5.2.6 on 2026-03-28 22:48

from django.db import migrations, models


def backfill_estado_timestamps(apps, schema_editor):
    """
    Rellena los timestamps de transición de estado para registros históricos.

    Estrategia por campo:
      fecha_en_despacho  → MAX(SolicitudDetalle.fecha_preparacion) si existe, si no created_at
      fecha_listo_despacho → MAX(Bulto.fecha_embalaje) con estado != cancelado si existe,
                             si no fecha_despachado (embalaje ≈ 0 h en KPI, pero el conteo iguala)
      fecha_despachado   → updated_at (mejor proxy disponible para solicitudes despachadas)
    """
    Solicitud = apps.get_model('solicitudes', 'Solicitud')
    SolicitudDetalle = apps.get_model('solicitudes', 'SolicitudDetalle')
    Bulto = apps.get_model('despacho', 'Bulto')

    # ── 1. fecha_despachado ──────────────────────────────────────────────────
    Solicitud.objects.filter(
        estado='despachado',
        fecha_despachado__isnull=True,
    ).update(fecha_despachado=models.F('updated_at'))

    # ── 2. fecha_en_despacho (para cualquier estado no pendiente) ────────────
    # Primero: desde MAX(fecha_preparacion) de detalles
    from django.db.models import Max, OuterRef, Subquery
    max_prep_sq = (
        SolicitudDetalle.objects
        .filter(solicitud=OuterRef('pk'), fecha_preparacion__isnull=False)
        .values('solicitud')
        .annotate(mp=Max('fecha_preparacion'))
        .values('mp')
    )
    Solicitud.objects.filter(
        estado__in=['en_despacho', 'listo_despacho', 'despachado'],
        fecha_en_despacho__isnull=True,
    ).update(fecha_en_despacho=Subquery(max_prep_sq))

    # Fallback: las que aún quedan sin fecha_en_despacho → created_at
    Solicitud.objects.filter(
        estado__in=['en_despacho', 'listo_despacho', 'despachado'],
        fecha_en_despacho__isnull=True,
    ).update(fecha_en_despacho=models.F('created_at'))

    # ── 3. fecha_listo_despacho ──────────────────────────────────────────────
    # Primero: desde MAX(Bulto.fecha_embalaje) de bultos no cancelados
    max_emb_sq = (
        Bulto.objects
        .filter(solicitud=OuterRef('pk'), fecha_embalaje__isnull=False)
        .exclude(estado='cancelado')
        .values('solicitud')
        .annotate(me=Max('fecha_embalaje'))
        .values('me')
    )
    Solicitud.objects.filter(
        estado__in=['listo_despacho', 'despachado'],
        fecha_listo_despacho__isnull=True,
    ).update(fecha_listo_despacho=Subquery(max_emb_sq))

    # Fallback: sin bultos con fecha_embalaje → usar fecha_despachado
    # (indica que el paso de embalaje no fue registrado; el KPI mostrará ~0 h para esos)
    Solicitud.objects.filter(
        estado__in=['listo_despacho', 'despachado'],
        fecha_listo_despacho__isnull=True,
        fecha_despachado__isnull=False,
    ).update(fecha_listo_despacho=models.F('fecha_despachado'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0016_alter_solicitud_tipo'),
        ('despacho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_despachado',
            field=models.DateTimeField(blank=True, help_text='Momento en que la solicitud pasó a estado despachado', null=True, verbose_name='Fecha despachada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_en_despacho',
            field=models.DateTimeField(blank=True, help_text='Momento en que la solicitud pasó a estado en_despacho', null=True, verbose_name='Fecha en despacho'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_listo_despacho',
            field=models.DateTimeField(blank=True, help_text='Momento en que la solicitud pasó a estado listo_despacho', null=True, verbose_name='Fecha listo para despacho'),
        ),
        migrations.RunPython(backfill_estado_timestamps, reverse_code=noop_reverse),
    ]
